services:
  db:
    image: postgres:16.3
    container_name: evplannerdb
    ports:
      - "${DB_PORT}:5432"
    restart: always
    environment:
      - POSTGRES_DB=${DB_DBNAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - evplanner-network

  server:
    image: evplanner-api:latest
    container_name: evplanner-sv
    ports:
      - "${API_PORT}:3004"
    volumes:
      - "./server:/api"
    environment:
      - DB_URL=jdbc:postgresql://evplannerdb:${DB_PORT}/${DB_DBNAME}
      - MONGO_URL=mongodb://evplmongo:${MONGO_PORT}/${MONGO_DBNAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}
    depends_on:
      - db
      - mongodb
    networks:
      - evplanner-network

  client:
    image: evplanner-client:latest
    container_name: evplanner-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${APP_PORT}:82"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    depends_on:
      - server
    networks:
      - evplanner-network

  mongodb:
    image: mongo:4.4.26
    container_name: evplmongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - evplanner-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "${MONGO_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_SERVER}
    networks:
      - evplanner-network

volumes:
  pgdata:

networks:
  evplanner-network:
    name: evplanner-network
    driver: bridge
