services:
  db:
    image: postgres:16.3
    container_name: evplanner-db
    ports:
      - "${DB_PORT}:5432"
    restart: always
    environment:
      - POSTGRES_DB=${DB_DBNAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - evplanner-network

  server:
    image: evplanner-api:latest
    container_name: evplanner-sv
    ports:
      - "${API_PORT}:3004"
    volumes:
      - "./server:/api"
    environment:
      - DB_URL=jdbc:postgresql://evplanner-db:${DB_PORT}/${DB_DBNAME}
      - DB_USER_NAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}
    depends_on:
      - db
    networks:
      - evplanner-network

  # client:
  #   image: client:latest
  #   container_name: evplanner-app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   ports:
  #     - "${APP_PORT}:82"
  #   volumes:
  #     - "./client:/app"
  #     - "/app/node_modules"
  #   depends_on:
  #     - server
  #   networks:
  #     - evplanner-network

volumes:
  pgdata:

networks:
  evplanner-network:
    driver: bridge
