version: "3.8"

services:
  client:
    build: ./client
    environment:
      WATCHPACK_POLLING: "true"
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - "./client:/app"
      - "/app/node_modules"

  server:
    build: ./server
    ports:
      - "${API_PORT}:3001"
    volumes:
      - "./server:/api"
      - "/api/node_modules"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    restart: always
    environment:
      - POSTGRES_DB=${DB_DBNAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
