version: "3.8"

services:
  client:
    build: ./client
    environment:
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
      - "/app/node_modules"

  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/api
      - /api/node_modules
