export enum Role {
  USER = "USER",
  ADMIN = "ADMIN",
  VENDOR = "VENDOR",
  EVT_OWNER = "EVT_OWNER",
  EVT_ORGANIZER = "EVT_ORGANIZER",
  EVT_COLLABORATOR = "EVT_COLLABORATOR",
  EVT_USER = "EVT_USER",
  EVT_ADMIN = "EVT_ADMIN",
  EVT_VENDOR = "EVT_VENDOR",
}
